name: CICD

on:
  push:
    branches:
      - Github-Actions
  pull_request:
    branches:
      - Github-Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create config.json
        run: |
          mkdir -p backend/config
          cat > backend/config/config.json << EOF
          {
            "development": {
              "username": "${{ secrets.DB_USERNAME }}",
              "password": "${{ secrets.DB_PASSWORD }}",
              "database": "${{ secrets.DB_DATABASE }}",
              "host": "${{ secrets.DB_HOST }}",
              "dialect": "mysql"
            },
            "test": {
              "username": "${{ secrets.DB_USERNAME }}",
              "password": "${{ secrets.DB_PASSWORD }}",
              "database": "${{ secrets.DB_DATABASE }}",
              "host": "${{ secrets.DB_HOST }}",
              "dialect": "mysql"
            },
            "production": {
              "username": "${{ secrets.DB_USERNAME }}",
              "password": "${{ secrets.DB_PASSWORD }}",
              "database": "${{ secrets.DB_DATABASE }}",
              "host": "${{ secrets.DB_HOST }}",
              "dialect": "mysql"
            }
          }
          EOF
          
      - name: Create .env file
        run: |
          cat > backend/.env << EOF
          PORT=${{ secrets.PORT || '5000' }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          EMAIL_USER=${{ secrets.EMAIL_USER }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          EOF

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/dailyrails:latest ./backend

      - name: List Docker images
        run: docker images

      - name: Push Docker image to Docker Hub
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/dailyrails:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}"/dailyrails:latest
            docker stop dailyrails || true
            docker rm dailyrails || true
            docker run -d --name dailyrails --network d73ec77ce253 -p 4000:4000 "${{ secrets.DOCKER_USERNAME }}"/dailyrails:latest

  database:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Copy SQL script to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          source: "Sample Data.sql"
          target: "/root/"
          
      - name: Execute SQL script on MySQL container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            echo "Executing SQL script on MySQL container..."
            docker exec -i mysql-server mysql -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_DATABASE }} < "/root/Sample Data.sql"
            echo "SQL script execution completed"